//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Krav.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ExceptionMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Krav.Resources.ExceptionMessages", typeof(ExceptionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty collection is not allowed..
        /// </summary>
        public static string EmptyCollection {
            get {
                return ResourceManager.GetString("EmptyCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty Guid is not allowed..
        /// </summary>
        public static string EmptyGuid {
            get {
                return ResourceManager.GetString("EmptyGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot compare items of type &apos;{0}&apos; and &apos;{1}&apos;.
        /// </summary>
        public static string IncomparableTypes {
            get {
                return ResourceManager.GetString("IncomparableTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is required to be a number but was Not a Number..
        /// </summary>
        public static string IsNotANumber {
            get {
                return ResourceManager.GetString("IsNotANumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type value is expected to be &apos;{0}&apos;, but was &apos;{1}&apos;..
        /// </summary>
        public static string IsNotExpectedType {
            get {
                return ResourceManager.GetString("IsNotExpectedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type value is expected to be &apos;{0}&apos;, but was null..
        /// </summary>
        public static string IsNotExpectedType_WasNull {
            get {
                return ResourceManager.GetString("IsNotExpectedType_WasNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected an expression that evaluates to false..
        /// </summary>
        public static string NotFalse {
            get {
                return ResourceManager.GetString("NotFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value expected to be greater than &apos;{0}&apos;, but was &apos;{1}&apos;..
        /// </summary>
        public static string NotGreaterThan {
            get {
                return ResourceManager.GetString("NotGreaterThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value expected to be greater than &apos;{0}&apos;, but was null..
        /// </summary>
        public static string NotGreaterThan_WasNull {
            get {
                return ResourceManager.GetString("NotGreaterThan_WasNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value expected to be greater than or equal to &apos;{0}&apos;, but was &apos;{1}&apos;..
        /// </summary>
        public static string NotGreaterThanOrEqualTo {
            get {
                return ResourceManager.GetString("NotGreaterThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value expected to be greater than or equal to &apos;{0}&apos;, but was null..
        /// </summary>
        public static string NotGreaterThanOrEqualTo_WasNull {
            get {
                return ResourceManager.GetString("NotGreaterThanOrEqualTo_WasNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value expected to be in range &apos;{0}&apos; - &apos;{1}&apos;, but was greater than &apos;{1}&apos;..
        /// </summary>
        public static string NotInRange_TooHigh {
            get {
                return ResourceManager.GetString("NotInRange_TooHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value expected to be in range &apos;{0}&apos; - &apos;{1}&apos;, but was less than &apos;{0}&apos;..
        /// </summary>
        public static string NotInRange_TooLow {
            get {
                return ResourceManager.GetString("NotInRange_TooLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value expected to be in range &apos;{0}&apos; - &apos;{1}&apos;, but was null..
        /// </summary>
        public static string NotInRange_WasNull {
            get {
                return ResourceManager.GetString("NotInRange_WasNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value expected to be less than &apos;{0}&apos;, but was &apos;{1}&apos;..
        /// </summary>
        public static string NotLessThan {
            get {
                return ResourceManager.GetString("NotLessThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value expected to be less than &apos;{0}&apos;, but was null..
        /// </summary>
        public static string NotLessThan_WasNull {
            get {
                return ResourceManager.GetString("NotLessThan_WasNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value expected  to be less than or equal to &apos;{0}&apos;, but was &apos;{1}&apos;..
        /// </summary>
        public static string NotLessThanOrEqualTo {
            get {
                return ResourceManager.GetString("NotLessThanOrEqualTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value expected to be less than or equal to &apos;{0}&apos;, but was null..
        /// </summary>
        public static string NotLessThanOrEqualTo_WasNull {
            get {
                return ResourceManager.GetString("NotLessThanOrEqualTo_WasNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The param is not of expected type. Expected: &apos;{0}&apos; but was &apos;{1}&apos;..
        /// </summary>
        public static string NotOfType {
            get {
                return ResourceManager.GetString("NotOfType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected an expression that evaluates to true..
        /// </summary>
        public static string NotTrue {
            get {
                return ResourceManager.GetString("NotTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value can not be null..
        /// </summary>
        public static string WasNull {
            get {
                return ResourceManager.GetString("WasNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value can not be null or empty..
        /// </summary>
        public static string WasNullOrEmpty {
            get {
                return ResourceManager.GetString("WasNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The string can not be null, empty or consist of only white-space..
        /// </summary>
        public static string WasNullOrWhiteSpace {
            get {
                return ResourceManager.GetString("WasNullOrWhiteSpace", resourceCulture);
            }
        }
    }
}
