// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("Krav.Simple")]
[assembly: AssemblyDescriptionAttribute("Snappy and readable preconditions")]
[assembly: AssemblyProductAttribute("Krav.Simple")]
[assembly: AssemblyVersionAttribute("1.1.0")]
[assembly: AssemblyFileVersionAttribute("1.1.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "1.1.0";
    }
}
