// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("Krav")]
[assembly: AssemblyDescriptionAttribute("Readable preconditions")]
[assembly: AssemblyProductAttribute("Krav")]
[assembly: AssemblyVersionAttribute("0.1.0")]
[assembly: AssemblyFileVersionAttribute("0.1.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.1.0";
    }
}
