// <auto-generated/>

using System.Reflection;

[assembly: AssemblyTitle("Krav")]
[assembly: AssemblyDescription("Readable preconditions")]
[assembly: AssemblyProduct("Krav")]
[assembly: AssemblyVersion("0.1.1")]
[assembly: AssemblyFileVersion("0.1.1")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.1.1";
    }
}
